services:
  postgres:
    image: postgres:16
    container_name: controle-estoque-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: controle_estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/ControleEstoque.Api/Database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
